repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff-check
        name: ruff check backend
        args:
          - --fix
          - --exit-non-zero-on-fix
        files: ^backend/.*\.py$
      - id: ruff-format
        name: ruff format backend
        files: ^backend/.*\.py$
