{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "the-experiment.fullname" . }}-redis
  labels:
    {{- include "the-experiment.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "the-experiment.redisSelectorLabels" . | nindent 4 }}
{{- end }}
